const INDEX_OF_BIRDS_DATA = 'INDEX_OF_BIRDS_DATA';
const SCORE = 'SCORE';
const IS_LEVEL_COMPLETE = 'IS_LEVEL_COMPLETE';
const POINTS = 'POINTS';
const LIST_ITEM_DATA = 'LIST_ITEM_DATA';

export {
  INDEX_OF_BIRDS_DATA, SCORE, IS_LEVEL_COMPLETE, POINTS, LIST_ITEM_DATA,
};
